title: "Derek Kedziora's Blog" 
author: Derek Kedziora
email: "derekkedziora@icloud.com"
description: "Derek Kedziora's blog about the tech world, UX, writing and anything else that's worth being opinated about"
github: derekkedziora
highlighter: rouge
markdown: kramdown
parse_block_html: false
url: https://derekkedziora.com
permalink: blog/:title
timezome: Europe/Kyiv
show_drafts: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      
  -    
    scope:
      path: ""
      type: "english-guides"
    values:
      english-guide: true

collections:
  pages:
    output: true

  english-guides:
    output: true
    permalink: english/:title

plugins:
  - jekyll-feed

feed:
  collections:
    - english-guides